'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BankNominal
    Public Property BankNominalId As Long
    Public Property CurrencyCode As String
    Public Property NominalCode As String
    Public Property Layout As String
    Public Property SageCompanyCode As String

End Class
