'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProcessPaymentHeader
    Public Property ID As System.Guid
    Public Property Currency As String
    Public Property [Date] As Nullable(Of Date)
    Public Property Company As String
    Public Property Processed As Nullable(Of Boolean)

    Public Overridable Property ProcessPaymentLines As ICollection(Of ProcessPaymentLine) = New HashSet(Of ProcessPaymentLine)

End Class
