'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ESSageSyncExampleEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ESSageSyncExampleEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property BankNominals() As DbSet(Of BankNominal)
    Public Overridable Property ProcessPaymentHeaders() As DbSet(Of ProcessPaymentHeader)
    Public Overridable Property ProcessPaymentLines() As DbSet(Of ProcessPaymentLine)

End Class
